"""Build a CLAUDE.md / AGENTS.md agent context file from a paid synthesis."""
from __future__ import annotations

import re
from typing import Any


def _clean(value: Any, fallback: str = '') -> str:
    """Return a plain string, rejecting raw JSON / None leaks."""
    if value is None or isinstance(value, (dict, list)):
        return fallback
    s = re.sub(r'\s+', ' ', str(value).strip())
    if re.search(r'\[object Object\]|\{\s*"[^"]+"\s*:|\bNone\b|\bundefined\b', s):
        return fallback
    return s


def _list_items(value: Any) -> list[str]:
    """Return a clean list of strings from a list, string, or None."""
    if not value:
        return []
    if isinstance(value, str):
        items = [_clean(i.strip()) for i in re.split(r'[;\n]|,\s', value) if i.strip()]
    elif isinstance(value, list):
        items = [_clean(v) for v in value if not isinstance(v, (dict, list))]
    else:
        return []
    return [i for i in items if i]


def build_agent_context(session: dict) -> str:
    """Produce a CLAUDE.md markdown string from the session's paid synthesis data."""
    analysis = session.get('analysis', {}) or {}
    synthesis = analysis.get('synthesis', {}) or {}
    repo_name = analysis.get('repo_name', 'this repository')

    lines: list[str] = []

    lines.append(f'# {repo_name} — Agent Context')
    lines.append('')
    lines.append('> Auto-generated by [CodeReceipt](https://codereceipt.site). '
                 'Drop this file in your repo root so Claude Code, Cursor, and other '
                 'AI tools instantly understand the codebase.')
    lines.append('')

    # Project overview
    what_built = _clean(synthesis.get('what_you_built'))
    if what_built:
        lines.append('## Project Overview')
        lines.append('')
        lines.append(what_built)
        lines.append('')

    # Architecture
    arch = _clean(synthesis.get('architecture_overview'))
    if arch:
        lines.append('## Architecture')
        lines.append('')
        lines.append(arch)
        lines.append('')

    # Key systems
    key_systems = synthesis.get('key_systems')
    if isinstance(key_systems, list) and key_systems:
        lines.append('## Key Systems')
        lines.append('')
        for system in key_systems:
            if isinstance(system, dict):
                name = _clean(system.get('name') or system.get('system'))
                desc = _clean(system.get('description') or system.get('role') or system.get('purpose'))
                if name:
                    lines.append(f'- **{name}**: {desc}' if desc else f'- **{name}**')
            elif isinstance(system, str):
                s = _clean(system)
                if s:
                    lines.append(f'- {s}')
        lines.append('')

    # Safe-to-touch rules
    _append_traffic_light(lines, synthesis, 'safe_green', '✅ Safe to modify freely')
    _append_traffic_light(lines, synthesis, 'safe_yellow', '⚠️ Modify with care')
    _append_traffic_light(lines, synthesis, 'safe_orange', '🔶 High-risk changes')
    _append_traffic_light(lines, synthesis, 'safe_red', '🚫 Do not modify without full review')

    # Environment variables
    env_vars = synthesis.get('environment_variables')
    if isinstance(env_vars, list) and env_vars:
        lines.append('## Environment Variables')
        lines.append('')
        for ev in env_vars:
            if isinstance(ev, dict):
                name = _clean(ev.get('name') or ev.get('key') or ev.get('variable'))
                purpose = _clean(ev.get('purpose') or ev.get('description'))
                if name:
                    lines.append(f'- `{name}`: {purpose}' if purpose else f'- `{name}`')
            elif isinstance(ev, str):
                s = _clean(ev)
                if s:
                    lines.append(f'- `{s}`')
        lines.append('')

    # Known risks
    risks: list[str] = []
    for field in ('risk_register', 'warning_lights'):
        items = synthesis.get(field)
        if isinstance(items, list):
            for item in items:
                if isinstance(item, dict):
                    desc = _clean(item.get('description') or item.get('risk') or item.get('warning'))
                    if desc:
                        risks.append(desc)
                elif isinstance(item, str):
                    s = _clean(item)
                    if s:
                        risks.append(s)
    if risks:
        lines.append('## Known Risks')
        lines.append('')
        for r in risks:
            lines.append(f'- {r}')
        lines.append('')

    # Conventions / codebase rules
    conventions = _list_items(synthesis.get('conventions') or synthesis.get('codebase_conventions'))
    if conventions:
        lines.append('## Conventions')
        lines.append('')
        for c in conventions:
            lines.append(f'- {c}')
        lines.append('')

    # AI handoff context
    ai_handoff = _clean(synthesis.get('ai_handoff_context') or synthesis.get('ai_handoff'))
    if ai_handoff:
        lines.append('## AI Handoff Notes')
        lines.append('')
        lines.append(ai_handoff)
        lines.append('')

    # Next actions
    next_actions = _list_items(synthesis.get('next_actions') or synthesis.get('recommended_next_steps'))
    if next_actions:
        lines.append('## Suggested Next Actions')
        lines.append('')
        for action in next_actions:
            lines.append(f'- [ ] {action}')
        lines.append('')

    return '\n'.join(lines)


def _append_traffic_light(lines: list[str], synthesis: dict, key: str, label: str) -> None:
    items = _list_items(synthesis.get(key))
    if items:
        lines.append(f'### {label}')
        for item in items:
            lines.append(f'- {item}')
        lines.append('')
