from app.models.analysis import RepoFile


def free_synthesis_prompt(chunk_outputs: list[str], stack: dict, options: dict) -> str:
    """Lightweight synthesis for the free tier — returns only Quick Start + Identity fields."""
    return (
        'You are producing a structured JSON object for a software owner\'s summary. '
        'Return ONLY a valid JSON object — no markdown fences, no preamble, no explanation. '
        'Write in plain English for a non-technical founder. '
        'Do NOT use first-person language, markdown, or bullet points inside values. '
        'When unsure, use "Not confidently detected." — never guess.\n\n'
        f'Detected stack: {stack}. Options: {options}.\n\n'
        'Return ONLY these four keys:\n'
        '{\n'
        '  "what_you_built": "1-2 sentence description of the project",\n'
        '  "app_type": "short label e.g. Web Application, API Service, CLI Tool",\n'
        '  "analysis_confidence": "high|medium|low",\n'
        '  "owner_quick_start": {\n'
        '    "what_it_does": "1-2 sentences on what the app does",\n'
        '    "who_uses_it": "1 sentence on the intended user",\n'
        '    "primary_flow": "1-2 sentences on the main user journey",\n'
        '    "main_parts": "1-2 sentences on the main moving parts",\n'
        '    "before_touching": "1-2 sentences on what to know before editing"\n'
        '  }\n'
        '}\n\n'
        'Chunk analyses:\n'
        + '\n\n'.join(chunk_outputs)
    )


def pass_one_prompt(files: list[RepoFile]) -> str:
    rendered = []
    for f in files:
        rendered.append(f"### {f.path}\n{f.content[:15000]}")

    paths_json = ', '.join(f'"{f.path}"' for f in files)

    return (
        'You are a technical writer producing a software owner\'s manual. '
        'Return ONLY a valid JSON object — no markdown fences, no preamble, no explanation. '
        'Map each file path to a 1-2 sentence plain-English description. '
        'Write for a non-technical founder. '
        'Do NOT use first-person language, markdown formatting, or bullet points in values. '
        'Do NOT invent dependencies or behaviours not evident in the code. '
        'Use "Not confidently detected." when a file\'s purpose is unclear. '
        'Each description must state what the file does and what breaks if it is removed.\n\n'
        f'Required keys: {paths_json}\n\n'
        'File contents:\n\n'
        + '\n\n'.join(rendered)
    )


def synthesis_prompt(chunk_outputs: list[str], stack: dict[str, list[str]], options: dict) -> str:
    return (
        'You are producing a structured JSON data object for a software owner\'s manual. '
        'Return ONLY a valid JSON object — no markdown fences, no preamble, no explanation. '
        'Write all values in plain English for a non-technical founder. '
        'Do NOT use first-person language, markdown formatting, bullet points, or conversational phrasing. '
        'Do NOT invent services, hosting providers, or dependencies not evident in the code. '
        'When unsure, use "Not confidently detected." — never guess or use generic filler. '
        'Mark confidence as: high, medium, or low.\n\n'
        f'Detected stack: {stack}. Options: {options}.\n\n'
        'Return a JSON object with EXACTLY these keys:\n\n'
        '{\n'
        '  "what_you_built": "1-2 sentence description of the project",\n'
        '  "app_type": "short label e.g. Web Application, API Service, CLI Tool",\n'
        '  "analysis_confidence": "high|medium|low",\n'
        '  "owner_quick_start": {\n'
        '    "what_it_does": "1-2 sentences on what the app does",\n'
        '    "who_uses_it": "1 sentence on the intended user",\n'
        '    "primary_flow": "1-2 sentences describing the main user journey",\n'
        '    "main_parts": "1-2 sentences on the main moving parts",\n'
        '    "before_touching": "1-2 sentences on what to understand before editing"\n'
        '  },\n'
        '  "architecture_overview": "2-3 sentences on how the system is structured",\n'
        '  "frontend_desc": "1-2 sentences or Not confidently detected.",\n'
        '  "backend_desc": "1-2 sentences or Not confidently detected.",\n'
        '  "database_desc": "1-2 sentences or Not confidently detected.",\n'
        '  "auth_desc": "1-2 sentences or Not confidently detected.",\n'
        '  "apis_desc": "1-2 sentences or Not confidently detected.",\n'
        '  "hosting_desc": "1-2 sentences or Not confidently detected.",\n'
        '  "external_services_desc": "1-2 sentences or Not confidently detected.",\n'
        '  "system_flow": "plain text flow e.g. User → Frontend → API → Database",\n'
        '  "key_systems": [\n'
        '    {\n'
        '      "name": "system name",\n'
        '      "what_it_does": "1-2 sentences",\n'
        '      "main_files": "comma-separated file paths",\n'
        '      "depends_on": "comma-separated dependencies or Not confidently detected.",\n'
        '      "if_it_breaks": "1 sentence",\n'
        '      "safe_edit": "1 sentence",\n'
        '      "risk_level": "low|medium|high|critical"\n'
        '    }\n'
        '  ],\n'
        '  "safe_green": ["list of files/areas safe for beginners"],\n'
        '  "safe_yellow": ["list of files/areas to edit carefully"],\n'
        '  "safe_orange": ["list of files/areas needing context"],\n'
        '  "safe_red": ["list of files/areas not to touch blindly"],\n'
        '  "running_costs": [\n'
        '    {\n'
        '      "service": "service name",\n'
        '      "what_it_powers": "1 sentence",\n'
        '      "what_to_monitor": "1 sentence",\n'
        '      "if_limits_reached": "1 sentence",\n'
        '      "cost_risk": "low|medium|high|unknown"\n'
        '    }\n'
        '  ],\n'
        '  "env_vars": [\n'
        '    {\n'
        '      "name": "VARIABLE_NAME",\n'
        '      "purpose": "1 sentence",\n'
        '      "required": true,\n'
        '      "is_secret": true,\n'
        '      "risk_level": "low|medium|high",\n'
        '      "if_missing": "1 sentence"\n'
        '    }\n'
        '  ],\n'
        '  "risk_register": [\n'
        '    {\n'
        '      "area": "risk area",\n'
        '      "severity": "low|medium|high|critical",\n'
        '      "why_it_matters": "1-2 sentences",\n'
        '      "where_to_inspect": "files or services to check",\n'
        '      "suggested_action": "1-2 sentences"\n'
        '    }\n'
        '  ],\n'
        '  "known_unknowns": [\n'
        '    {\n'
        '      "item": "what could not be confirmed",\n'
        '      "confidence": "detected|inferred|not found",\n'
        '      "why_it_matters": "1 sentence"\n'
        '    }\n'
        '  ],\n'
        '  "concept_glossary": [\n'
        '    {"term": "term name", "tag": "category label", "definition": "plain-English definition"}\n'
        '  ],\n'
        '  "next_actions": ["action 1", "action 2", "action 3", "action 4", "action 5"],\n'
        '  "ai_handoff_context": "2-3 sentences summarising the project for an AI agent handoff",\n'
        '  "maintenance_guide": "2-3 sentences of practical maintenance advice",\n'
        '  "file_reference": "1 sentence describing the codebase files collectively"\n'
        '}\n\n'
        'Chunk analyses:\n'
        + '\n\n'.join(chunk_outputs)
    )
